# Importerer pandas og leser inn filene

In [1]:
import pandas as pd
df = pd.read_excel('dataTableStudents_I.xlsx')
df2 = pd.read_excel('dataTableStudents_II.xlsx')

In [2]:
df3 = df.join(df2.drop(columns='timeVectRelMinutes'))
df3

,timeVectRelMinutes,battery_0__actualPower,thrusterAndPropulsion,sumEngMdoPower,hotelLoad,shorePowerEstimated,numberOfMdoEnginesRunning,operationId,dpMode,engMdoPower_0_,...,engMdoPower_3_,engMdoPerformance_0_,engMdoPerformance_1_,engMdoPerformance_2_,engMdoPerformance_3_,engMdoConsumption_0_,engMdoConsumption_1_,engMdoConsumption_2_,engMdoConsumption_3_,speedOverGround
0,0.000000,0,0.0,0,250.0,250,0,6,0,0,...,0,0.0,0.000,0,0.000,0.0,0.00,0.0,0.00,0.094
1,0.016650,0,0.0,0,250.0,250,0,6,0,0,...,0,0.0,0.000,0,0.000,0.0,0.00,0.0,0.00,0.022
2,0.033317,0,0.0,0,250.0,250,0,6,0,0,...,0,0.0,0.000,0,0.000,0.0,0.00,0.0,0.00,0.151
3,0.049983,1,0.0,0,250.0,249,0,6,0,0,...,0,0.0,0.000,0,0.000,0.0,0.00,0.0,0.00,0.080
4,0.066667,1,0.0,0,250.0,249,0,6,0,0,...,0,0.0,0.000,0,0.000,0.0,0.00,0.0,0.00,0.080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604795,10079.916783,-20,1386.0,2037,631.0,0,2,3,0,0,...,1043,0.0,222.037,0,210.362,0.0,255.15,0.0,253.65,5.500
604796,10079.933483,11,1408.0,2009,612.0,0,2,3,0,0,...,952,0.0,212.690,0,235.104,0.0,259.90,0.0,258.75,5.240
604797,10079.950117,11,1430.0,2116,697.0,0,2,3,0,0,...,1062,0.0,216.045,0,213.359,0.0,263.25,0.0,261.95,6.727
604798,10079.966800,17,1430.0,2015,602.0,0,2,3,0,0,...,996,0.0,223.550,0,222.416,0.0,263.35,0.0,256.10,7.917
604799,10079.983450,-1,1386.0,1954,567.0,0,2,3,0,0,...,969,0.0,226.261,0,223.972,0.0,257.65,0.0,250.90,7.770

# Endrer navn på og gjør om tid-kolonnen til datetime

## datetime er en standardisert måte å vise tid på, trengs for å bruke funksjonen resample() til å aggregere

In [3]:
df3.rename(columns= {'timeVectRelMinutes': 'datetime'}, inplace=True)
df3['datetime'] = pd.to_datetime(df3['datetime'], unit='m', origin='2020-01-30')

# Resampler til minutt- og timesoppløsning

In [5]:
min_df = df3.resample('min', on='datetime').mean().reset_index()
hour_df = df3.resample('60min', on='datetime').mean().reset_index()

# Lagrer filene som nye excel-filer

In [6]:
min_df.to_excel('data_full_minres.xlsx')
hour_df.to_excel('data_full_hourres.xlsx')
df3.to_excel('data_full_sekres.xlsx')

In [13]:
df3.to_excel('data_full_sekres.xlsx')

# Oppretter ny dataframe med minuttsoppløsning

# Eksporterer data i minuttsoppløsning til excel

In [ ]:
min_full = minute_df.join(minute_df2.drop(columns='datetime'))

In [3]:
df.rename(columns= {'timeVectRelMinutes': 'datetime'}, inplace=True)
df['datetime'] = pd.to_datetime(df['datetime'], unit='m', origin='2020-01-30')
df2.rename(columns= {'timeVectRelMinutes': 'datetime'}, inplace=True)
df2['datetime'] = pd.to_datetime(df2['datetime'], unit='m', origin='2020-01-30')

In [5]:
hour_df = df.resample('60min', on='datetime').mean().reset_index()
hour_df2 = df2.resample('60min', on='datetime').mean().reset_index()

In [7]:
hour_df3 = hour_df.join(hour_df2.drop(columns='datetime'))
hour_df3.to_excel('data_full_hourres.xlsx')

In [8]:
hour_df3

,datetime,battery_0__actualPower,thrusterAndPropulsion,sumEngMdoPower,hotelLoad,shorePowerEstimated,numberOfMdoEnginesRunning,operationId,dpMode,engMdoPower_0_,...,engMdoPower_2_,engMdoPower_3_,engMdoPerformance_0_,engMdoPerformance_1_,engMdoPerformance_2_,engMdoPerformance_3_,engMdoConsumption_0_,engMdoConsumption_1_,engMdoConsumption_2_,engMdoConsumption_3_
0,2020-01-30 00:00:00,0.000000,0.000000,0.000000,250.000000,250.000000,0.000000,6.000000,0.000000,0.0,...,0.0,0.000000,0.0,0.000000,0,0.000000,0.0,0.000000,0.0,0.000000
1,2020-01-30 01:00:00,0.001944,0.000000,0.000000,250.000000,249.998056,0.000000,6.000000,0.000000,0.0,...,0.0,0.000000,0.0,0.000000,0,0.000000,0.0,0.000000,0.0,0.000000
2,2020-01-30 02:00:00,-0.002222,0.000000,0.000000,250.000000,250.002222,0.000000,6.000000,0.000000,0.0,...,0.0,0.000000,0.0,0.000000,0,0.000000,0.0,0.000000,0.0,0.000000
3,2020-01-30 03:00:00,0.010556,0.000000,0.000000,250.000000,249.989444,0.000000,6.000000,0.000000,0.0,...,0.0,0.000000,0.0,0.000000,0,0.000000,0.0,0.000000,0.0,0.000000
4,2020-01-30 04:00:00,-0.001944,0.000000,0.000000,250.000000,250.001944,0.000000,6.000000,0.000000,0.0,...,0.0,0.000000,0.0,0.000000,0,0.000000,0.0,0.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,2020-02-05 19:00:00,28.979167,1186.887778,1716.515556,558.606944,0.000000,1.000000,3.000000,0.000000,0.0,...,0.0,0.000000,0.0,212.286921,0,0.000000,0.0,420.953403,0.0,0.000000
164,2020-02-05 20:00:00,29.767222,1189.454444,1719.979167,560.291944,0.000000,1.000000,3.000000,0.000000,0.0,...,0.0,0.000000,0.0,211.749076,0,0.000000,0.0,420.751292,0.0,0.000000
165,2020-02-05 21:00:00,25.102500,1178.472778,1705.256667,551.886389,0.000000,1.000000,3.000000,0.000000,0.0,...,0.0,0.000000,0.0,211.908229,0,0.000000,0.0,417.454139,0.0,0.000000
166,2020-02-05 22:00:00,-128.794722,836.586197,1461.023333,495.642414,0.000000,1.886111,31.654167,0.561389,0.0,...,0.0,635.226389,0.0,251.993469,0,226.913168,0.0,222.732625,0.0,175.224944
167,2020-02-05 23:00:00,1.091667,1372.017778,1975.237222,604.311111,0.000000,2.000000,3.000000,0.000000,0.0,...,0.0,986.192778,0.0,223.620242,0,219.939318,0.0,255.395542,0.0,250.310333

In [15]:
op1 = hour_df3.loc[hour_df3['operationId']==1]
op1

Empty DataFrame
Columns: [datetime, battery_0__actualPower, thrusterAndPropulsion, sumEngMdoPower, hotelLoad, shorePowerEstimated, numberOfMdoEnginesRunning, operationId, dpMode, engMdoPower_0_, engMdoPower_1_, engMdoPower_2_, engMdoPower_3_, engMdoPerformance_0_, engMdoPerformance_1_, engMdoPerformance_2_, engMdoPerformance_3_, engMdoConsumption_0_, engMdoConsumption_1_, engMdoConsumption_2_, engMdoConsumption_3_]
Index: []

[0 rows x 21 columns]